### ISSUE TITLE
Pdf compiling

### ISSUE THREAD

**Issue by GIGASHAB** [joaomlourenco/novathesis_word#3]
Hi,

I´ve just started to write my dissertation in the overleaf. It is an error while compiling the pdf:
"
This compile didn’t produce a PDF. This can happen if:
There is an unrecoverable LaTeX error. If there are LaTeX errors shown below or in the raw logs, please try to fix them and compile again.
The document environment contains no content. If it’s empty, please add some content and compile again.
This project contains a file called output.pdf. If that file exists, please rename it and compile again. 
"

**Comment by joaomlourenco** [comment]
You are posting in the wrong project.  **This project is only for the Word version of the templates**.
Please repost in the right project:
https://github.com/joaomlourenco/novathesis
Thank.
